
/* Drop Tables */

DROP TABLE AUCTION_IMG CASCADE CONSTRAINTS;
DROP TABLE AUCTION_LIKE CASCADE CONSTRAINTS;
DROP TABLE AUCTION_PRICE CASCADE CONSTRAINTS;
DROP TABLE AUCTION_REPORT CASCADE CONSTRAINTS;
DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE CHATROOM CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE AUCTION_LIST CASCADE CONSTRAINTS;
DROP TABLE TOWN_COMMENTS CASCADE CONSTRAINTS;
DROP TABLE TOWN_IMG CASCADE CONSTRAINTS;
DROP TABLE TOWN_LIKE CASCADE CONSTRAINTS;
DROP TABLE TOWN_REPORT CASCADE CONSTRAINTS;
DROP TABLE TOWN_LIST CASCADE CONSTRAINTS;
DROP TABLE ADDRESS_LIST CASCADE CONSTRAINTS;
DROP TABLE AUTHORITY_SECURITY CASCADE CONSTRAINTS;
DROP TABLE PAYLOG CASCADE CONSTRAINTS;
DROP TABLE ZABARAPAY CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;
DROP TABLE SEARCHLOG CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_ADDRESS_LIST_ADDRNO;
DROP SEQUENCE SEQ_AUCTION_IMG_IMAGENO;
DROP SEQUENCE SEQ_AUCTION_LIST_ACTION_NO;
DROP SEQUENCE SEQ_AUCTION_LIST_ADDRESS_AUCTION_ADDRESS_NO;
DROP SEQUENCE SEQ_AUCTION_LIST_AUCTION_NO;
DROP SEQUENCE SEQ_AUCTION_REPORT_AUCTION_REPORT_NO;
DROP SEQUENCE SEQ_CHATROOM_ROOM_NO;
DROP SEQUENCE SEQ_MEMBERS_USERNO;
DROP SEQUENCE SEQ_NEW_TABLE_AUCTION_REPORT_NO;
DROP SEQUENCE SEQ_PAYLOG_LOGNO;
DROP SEQUENCE SEQ_PRODUCT_IMG_IMAGENO;
DROP SEQUENCE SEQ_PRODUCT_LIST_AUCTION_NO;
DROP SEQUENCE SEQ_PRODUCT_LIST_PRODUCT_NO;
DROP SEQUENCE SEQ_SEARCHLOG_LOG_NO;
DROP SEQUENCE SEQ_TOWN_COMMENTS_COMMENT_NO;
DROP SEQUENCE SEQ_TOWN_IMG_IMAGENO;
DROP SEQUENCE SEQ_TOWN_LIST_TOWNLIST_NO;
DROP SEQUENCE SEQ_TOWN_REPORT_TOWN_REPORT_NO;
DROP SEQUENCE SEQ_ZABARAPAY_PAYNO;




/* Create Sequences */

CREATE SEQUENCE SEQ_ADDRESS_LIST_ADDRNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AUCTION_IMG_IMAGENO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AUCTION_LIST_ACTION_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AUCTION_LIST_ADDRESS_AUCTION_ADDRESS_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AUCTION_LIST_AUCTION_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AUCTION_REPORT_AUCTION_REPORT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CHATROOM_ROOM_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MEMBERS_USERNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_NEW_TABLE_AUCTION_REPORT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAYLOG_LOGNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PRODUCT_IMG_IMAGENO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PRODUCT_LIST_AUCTION_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PRODUCT_LIST_PRODUCT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SEARCHLOG_LOG_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TOWN_COMMENTS_COMMENT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TOWN_IMG_IMAGENO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TOWN_LIST_TOWNLIST_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TOWN_REPORT_TOWN_REPORT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_ZABARAPAY_PAYNO INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE ADDRESS_LIST
(
	ADDRNO number NOT NULL,
	USERNO number NOT NULL,
	SIMPLEADDRESS nvarchar2(20) NOT NULL,
	FULLADDRESS nvarchar2(50),
	LATITUDE float NOT NULL,
	LONGITUDE float NOT NULL,
	AUCTION_NO number,
	PRIMARY KEY (ADDRNO)
);


CREATE TABLE AUCTION_IMG
(
	IMAGENO number NOT NULL,
	IMAGENAME nvarchar2(500) NOT NULL,
	AUCTION_NO number NOT NULL,
	PRIMARY KEY (IMAGENO)
);


CREATE TABLE AUCTION_LIKE
(
	USERNO number NOT NULL,
	AUCTION_NO number NOT NULL
);


CREATE TABLE AUCTION_LIST
(
	AUCTION_NO number NOT NULL,
	USERNO number NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(200) NOT NULL,
	CATEGORY nvarchar2(50) NOT NULL,
	LIKES number DEFAULT 0 NOT NULL,
	POSTDATE timestamp DEFAULT SYSDATE NOT NULL,
	ADDRNO number NOT NULL,
	ENDDATE timestamp NOT NULL,
	STATUS nvarchar2(50),
	PRIMARY KEY (AUCTION_NO)
);


CREATE TABLE AUCTION_PRICE
(
	UPPER_PRICE number NOT NULL,
	BASE_PRICE number NOT NULL,
	UPPER_USER_NO number,
	AUCTION_NO number NOT NULL
);


CREATE TABLE AUCTION_REPORT
(
	AUCTION_REPORT_NO number NOT NULL,
	AUCTION_NO number NOT NULL,
	REPORT_USERNO number NOT NULL,
	AUCTION_REPORT_CATEGORY nvarchar2(500) NOT NULL,
	AUCTION_REPORT_CONTENT nvarchar2(1000) NOT NULL,
	PRIMARY KEY (AUCTION_REPORT_NO)
);


CREATE TABLE AUTHORITY_SECURITY
(
	USERNO number NOT NULL,
	AUTHORITY varchar2(20) DEFAULT 'ROLE_USER' NOT NULL,
	ENABLED number DEFAULT 1 NOT NULL
);


CREATE TABLE CHATROOM
(
	ROOM_NO number NOT NULL,
	AUCTION_NO number,
	TOWNLIST_NO number,
	WRITEUSERNO number NOT NULL,
	USERNO number NOT NULL,
	CHATCONTENT nvarchar2(500),
	SENDTIME timestamp DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (ROOM_NO)
);


CREATE TABLE CHAT_MESSAGE
(
	ROOM_NO number NOT NULL,
	SENDUSERNO number NOT NULL,
	UNREAD_COUNT number NOT NULL,
	CHATCONTENT nvarchar2(500) NOT NULL,
	SENDTIME timestamp DEFAULT SYSDATE NOT NULL,
	img nvarchar2(50)
);


CREATE TABLE MEMBERS
(
	USERNO number NOT NULL,
	EMAIL nvarchar2(50) UNIQUE,
	PASSWORD nvarchar2(50),
	NICKNAME nvarchar2(20),
	PHONENUMBER nvarchar2(50) UNIQUE,
	PROFILE_IMG nvarchar2(200),
	PLATFORM nvarchar2(50) NOT NULL,
	PRIMARY KEY (USERNO)
);


CREATE TABLE PAYLOG
(
	LOGNO number NOT NULL,
	PAYNO number NOT NULL,
	DEPOSIT number,
	WITHDRAW number,
	BALANCE number NOT NULL,
	PRIMARY KEY (LOGNO)
);


CREATE TABLE REVIEW
(
	REVIEW_NO number NOT NULL,
	REVIEW_CONTENT nvarchar2(2000) NOT NULL,
	REVIEW_STAR number NOT NULL,
	USER_NO number NOT NULL,
	AUCTION_NO number NOT NULL,
	PRIMARY KEY (REVIEW_NO)
);


CREATE TABLE SEARCHLOG
(
	LOG_NO number NOT NULL,
	SEARCH_WORD nvarchar2(100) NOT NULL,
	SEARCH_COUNT number NOT NULL,
	PRIMARY KEY (LOG_NO)
);


CREATE TABLE TOWN_COMMENTS
(
	COMMENT_NO number NOT NULL,
	TOWNLIST_NO number NOT NULL,
	COMMENT_CONTENT nvarchar2(500) NOT NULL,
	COMMENT_USERNO number NOT NULL,
	COMMENT_POSTDATE timestamp DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (COMMENT_NO)
);


CREATE TABLE TOWN_IMG
(
	IMAGENO number NOT NULL,
	IMAGENAME nvarchar2(500) NOT NULL,
	TOWNLIST_NO number NOT NULL,
	PRIMARY KEY (IMAGENO)
);


CREATE TABLE TOWN_LIKE
(
	USERNO number NOT NULL,
	TOWNLIST_NO number NOT NULL
);


CREATE TABLE TOWN_LIST
(
	TOWNLIST_NO number NOT NULL,
	USERNO number NOT NULL,
	TITLE nvarchar2(20) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	VIEWCOUNT number NOT NULL,
	POSTDATE timestamp DEFAULT SYSDATE NOT NULL,
	CATEGORY nvarchar2(50),
	ADDRNO number NOT NULL,
	LIKES number NOT NULL,
	PRIMARY KEY (TOWNLIST_NO)
);


CREATE TABLE TOWN_REPORT
(
	TOWN_REPORT_NO number NOT NULL,
	TOWNLIST_NO number NOT NULL,
	TOWN_REPORT_CATEGORY nvarchar2(500) NOT NULL,
	TOWN_REPORT_CONTENT nvarchar2(1000) NOT NULL,
	REPORT_USERNO number NOT NULL,
	PRIMARY KEY (TOWN_REPORT_NO)
);


CREATE TABLE ZABARAPAY
(
	PAYNO number NOT NULL,
	USERNO number NOT NULL,
	PRIMARY KEY (PAYNO)
);



/* Create Foreign Keys */

ALTER TABLE AUCTION_LIST
	ADD FOREIGN KEY (ADDRNO)
	REFERENCES ADDRESS_LIST (ADDRNO)
    on delete cascade 
;


ALTER TABLE TOWN_LIST
	ADD FOREIGN KEY (ADDRNO)
	REFERENCES ADDRESS_LIST (ADDRNO)
    on delete cascade 
;


ALTER TABLE AUCTION_IMG
	ADD FOREIGN KEY (AUCTION_NO)
	REFERENCES AUCTION_LIST (AUCTION_NO)
    on delete cascade 
;


ALTER TABLE AUCTION_LIKE
	ADD FOREIGN KEY (AUCTION_NO)
	REFERENCES AUCTION_LIST (AUCTION_NO)
    on delete cascade 
;


ALTER TABLE AUCTION_PRICE
	ADD FOREIGN KEY (AUCTION_NO)
	REFERENCES AUCTION_LIST (AUCTION_NO)
	on delete cascade 
;


ALTER TABLE AUCTION_REPORT
	ADD FOREIGN KEY (AUCTION_NO)
	REFERENCES AUCTION_LIST (AUCTION_NO)
    on delete cascade 
;


ALTER TABLE CHATROOM
	ADD FOREIGN KEY (AUCTION_NO)
	REFERENCES AUCTION_LIST (AUCTION_NO)
    on delete cascade 
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (AUCTION_NO)
	REFERENCES AUCTION_LIST (AUCTION_NO)
    on delete cascade 
;


ALTER TABLE CHAT_MESSAGE
	ADD FOREIGN KEY (ROOM_NO)
	REFERENCES CHATROOM (ROOM_NO)
    on delete cascade 
;


ALTER TABLE AUCTION_LIKE
	ADD FOREIGN KEY (USERNO)
	REFERENCES MEMBERS (USERNO)
    on delete cascade 
;


ALTER TABLE AUTHORITY_SECURITY
	ADD FOREIGN KEY (USERNO)
	REFERENCES MEMBERS (USERNO)
    on delete cascade 
;


ALTER TABLE TOWN_LIKE
	ADD FOREIGN KEY (USERNO)
	REFERENCES MEMBERS (USERNO)
    on delete cascade 
;


ALTER TABLE TOWN_LIST
	ADD FOREIGN KEY (USERNO)
	REFERENCES MEMBERS (USERNO)
    on delete cascade 
;


ALTER TABLE ZABARAPAY
	ADD FOREIGN KEY (USERNO)
	REFERENCES MEMBERS (USERNO)
    on delete cascade 
;


ALTER TABLE CHATROOM
	ADD FOREIGN KEY (TOWNLIST_NO)
	REFERENCES TOWN_LIST (TOWNLIST_NO)
    on delete cascade 
;


ALTER TABLE TOWN_COMMENTS
	ADD FOREIGN KEY (TOWNLIST_NO)
	REFERENCES TOWN_LIST (TOWNLIST_NO)
    on delete cascade 
;


ALTER TABLE TOWN_IMG
	ADD FOREIGN KEY (TOWNLIST_NO)
	REFERENCES TOWN_LIST (TOWNLIST_NO)
    on delete cascade 
;


ALTER TABLE TOWN_LIKE
	ADD FOREIGN KEY (TOWNLIST_NO)
	REFERENCES TOWN_LIST (TOWNLIST_NO)
    on delete cascade 
;


ALTER TABLE TOWN_REPORT
	ADD FOREIGN KEY (TOWNLIST_NO)
	REFERENCES TOWN_LIST (TOWNLIST_NO)
    on delete cascade 
;


ALTER TABLE PAYLOG
	ADD FOREIGN KEY (PAYNO)
	REFERENCES ZABARAPAY (PAYNO)
    on delete cascade 
;


